### ISSUE TITLE
Better interface for TabSettings

### ISSUE THREAD

**Issue by BenMusch** [MIT-Tab/mit-tab#248]
Right now tab settings are kinda a bad UX because it requires people use the documentation and read things carefully, have no typos, etc.

I think we can improve this by having a `/settings` page where we have a better UI controlled by a YAML file. For example

```yaml
  judges_public:
    type: boolean
    description: Is the judge list publicly visible?
    default: 0
 hit_team_before:
   type: integer
   description: Penalty in the pairing algorithm for hitting a team you have already hit. Lower values are a stronger penalty
    default: -100000
```

You can imagine a view which reads this file and renders a form based on this configuration
