### ISSUE TITLE
Admin Interface Broken in Prod

### ISSUE THREAD

**Issue by JoeyRubas** [MIT-Tab/mit-tab#360]
Prod:

![Image](https://github.com/user-attachments/assets/ae0129b3-9c60-437e-a331-3836f63e1ba9)

Local:

![Image](https://github.com/user-attachments/assets/6f642f26-cea5-45ca-8948-f5a78fed15d4)

Could be a deployer issue. Haven't done any investigation

**Comment by BenMusch** [comment]
Definitely a deployer issue, likely with static asset routing. TAL now and will share how I fix for the sake of documenting

**Comment by BenMusch** [comment]
Actual, may be a build issue within mit-tab. Will have to check out on my personal laptop later. What I've got so far:

First step: looking at the failing request in the network panel. Seems to be going to `/static/admin/css/base.css`

![Image](https://github.com/user-attachments/assets/b586af09-ce92-4659-9899-c1eb4edaab42)

Compare this to a page that's working and see that it's `/static/webpack_bundles/main.css`

![Image](https://github.com/user-attachments/assets/212f7eee-0ec3-422f-bea8-909c7f87dde2)

This is the relevant config from the app spec:

```yaml
ingress:
  rules:
  - component:
      name: web
    match:
      path:
        prefix: /
  - component:
      name: static
    match:
      path:
        prefix: /static
# ...
static_sites:
- dockerfile_path: Dockerfile.static
  github:
    branch: master
    repo: MIT-Tab/mit-tab
  name: static
  output_dir: /var/www/tab/assets
```

What that config means is:
 - The static files will be generated from the `Dockerfile.static` container, and the files at `/var/www/tab/assets` will be routed to at `{url}/static`, e.g. `/var/www/tab/assets/main.css` will load if you go to `{url}/static/main.css`

So to see what's going wrong, I build the docker container: `docker build -f Dockerfile.static -t tab-static .` (build the container and tag it with `tab-static`

Then I get a shell to the container: `docker run -it tab-static bash`

And it suspiciously doesn't show any admin assets:

```
docker run -it tab-static bash
root@6ca31ae0a461:/var/www/tab# ls
Pipfile  Pipfile.lock  assets  bin  manage.py  mittab  node_modules  package-lock.json	package.json  setup.py	staticfiles  webpack-stats.json  webpack.config.js
root@6ca31ae0a461:/var/www/tab# ls assets/
css  img  js  webpack_bundles
root@6ca31ae0a461:/var/www/tab# ls assets/css/
app.scss  pairing-display.scss	public-display.scss
```

So, either in settings.py or `Dockerfile.static`, we're likely messing up some config that stops the admin assets from being generated _or_ we're accidentally over-writing them
